### ISSUE TITLE
Post Method Doesn't Work

### ISSUE THREAD

**Issue by KingCh1ll** [yonathan06/fastify-now#35] opened 2023-10-03 15:14 UTC
Hi there! I just migrated from Express to Fastify, and found your plugin. However, it seems that although the GET feature works, the POST feature does not. The POST method returns 405, which means invalid method. I never return a 405 status code. If I am doing something wrong, please feel free to let me know.

Code:
export const GET: NowRequestHandler<{
    Querystring: {
        ["hahayes"]?: string,
    }
}> = async (req, reply) => console.log("we got GET request");

export const POST: NowRequestHandler<{
    Body: {
      ["yes"]?: string
    }
}> = async (req, reply) => {
    console.log("body", req.body) // this is never logged :(
};

**Comment by KingCh1ll** [comment] 2023-10-03 20:02
> Hi 405 is not 404: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405 I guess your code doesn't send the right method string

Hi, sorry I meant that I never return a 405 status code. I assumed it was your code that did that? 404 is page not found, 405 is that the method is wrong, even though I have POST exported.

**Comment by KingCh1ll** [comment] 2023-10-04 01:24
Hi, quick update. It seems this code is working on my Windows laptop, however the same code does not work on my Linux VPS. It seems only GET requests can go through, and any methods does not work after adding GET. I will continue to debug this problem.

**Comment by yonathan06** [comment] 2023-10-04 06:31
closing for now, feel free to reopen if you find an issue

**Closed by yonathan06** 2023-10-04 06:31 UTC

**Comment by KingCh1ll** [comment] 2023-10-04 18:50
> closing for now, feel free to reopen if you find an issue

This is still an issue. It may not work on my Linux server but it works on my Windows laptop.

**Comment by yonathan06** [comment] 2023-10-05 06:37
Please share your front-end code, or a reproducible code that generates this error, I couldn't reproduce it locally

**Comment by KingCh1ll** [comment] 2023-10-06 19:56
Hi there, after more testing I found the problem. For whatever reason, .build folder does not exist on my linux VPS. However, on Windows it does 🤔

**Comment by KingCh1ll** [comment] 2023-10-06 19:56
A reinstall of node_modules does the same. Something isn't right.

**Comment by KingCh1ll** [comment] 2023-10-06 22:33
Hi, I just ended up building my own API handler. You can leave this post closed. I am not using your NPM package anymore.

**Comment by yonathan06** [comment] 2023-10-08 07:51
the .build folder issue is not part of the package, you should debug your build scripts
